import Mathlib.Order.Basic
import Mathlib.Order.Ideal
import Mathlib.Order.Lattice
import Mathlib.Order.Notation
import Mathlib.Order.SetNotation
import Mathlib.Order.CompleteLattice.Basic
import Mathlib.Order.CompleteLattice.Defs
import Mathlib.Order.Hom.CompleteLattice
import Mathlib.Order.WellFounded
import Mathlib.Order.UpperLower.Basic
import Mathlib.Order.UpperLower.CompleteLattice
import Mathlib.Tactic.TFAE
import Mathlib.Order.Preorder.Chain
import Mathlib.Order.Sublattice
import Mathlib.Data.Finset.Lattice.Fold
import Mathlib.Data.Set.Finite.Basic

variable {α β L K P Q : Type*}


-- manually completed by Tally and Alex
/--
The Connecting Lemma
-/
lemma lemma_2_8 [Lattice L] (a b : L) : List.TFAE [a ≤ b, a ⊔ b = b, a ⊓ b = a] := by
  tfae_have 1 → 2 := by
    intro h
    rw [sup_eq_right]
    exact h
  tfae_have 2 → 3 := by
    intro h
    have h' : a ⊓ (a ⊔ b) = a ⊓ b :=
      congrArg (fun x => a ⊓ x) h
    rw [inf_sup_self] at h'
    exact h'.symm
  tfae_have 3 → 1 := by
    intro h
    rw [← inf_eq_left]
    exact h
  tfae_finish



theorem theorem_2_19_i [Lattice L] [Lattice K] (f : L → K) : List.TFAE [
  Monotone f,
  ∀ a b, f (a ⊔ b) ≥  f a ⊔ f b,
  ∀ a b, f (a ⊓ b) ≤  f a ⊓ f b] := by
    tfae_have 1 → 2 := by sorry
    tfae_have 2 → 3 := by sorry
    tfae_have 3 → 1 := by sorry
    tfae_finish


def IsLatticeHom [Lattice L] [Lattice K] (f : L → K) : Prop :=
  (∀ x y, f (x ⊔ y) = f x ⊔ f y) ∧ (∀ x y, f (x ⊓ y) = f x ⊓ f y)

theorem theorem_2_19_i' [Lattice L] [Lattice K] (f : L → K) :
  IsLatticeHom f → Monotone f := by
    sorry


-- completed by cursor agent with MCP and lean4-skills
-- ∃ e : α ≃o β, e.toFun = f means that there exists an order isomorphism between α and β
-- such that the function f is the underlying function of the order isomorphism
theorem proposition_2_19_ii [Lattice α] [Lattice β] (f : α → β) :
  (∃ e : α ≃o β, e.toFun = f) ↔
  ((Function.Bijective f) ∧
    (∀ x y, f (x ⊓ y) = f x ⊓ f y) ∧
    (∀ x y, f (x ⊔ y) = f x ⊔ f y)) := by
  constructor
  · rintro ⟨e, rfl⟩
    exact ⟨Equiv.bijective (e : α ≃ β), e.map_inf, e.map_sup⟩
  · rintro ⟨hf, _hinf, hsup⟩
    have hreflect : ∀ {a b : α}, f a ≤ f b → a ≤ b := by
      intro a b hab
      have hfb : f (a ⊔ b) = f b := by rw [hsup, sup_eq_right.2 hab]
      have hab' : a ⊔ b = b := hf.injective hfb
      rw [← hab']
      exact le_sup_left
    let e : α ≃ β := Equiv.ofBijective f hf
    refine ⟨e.toOrderIso ?_ ?_, rfl⟩
    · intro a b hab
      dsimp [e]
      rw [← sup_eq_right.2 hab, hsup]
      exact le_sup_left
    · intro a b hab
      apply hreflect
      calc
        f (e.symm a) = a := Equiv.apply_symm_apply e a
        _ ≤ b := hab
        _ = f (e.symm b) := (Equiv.apply_symm_apply e b).symm


-- definition of a lattice isomorphism generated by Cursor agent with mcp and lean4-skills
/-- `f` is a lattice isomorphism: bijective and preserves binary meet and join -/
def IsLatticeIso [Lattice α] [Lattice β] (f : α → β) : Prop :=
  Function.Bijective f ∧ (∀ x y, f (x ⊓ y) = f x ⊓ f y) ∧ (∀ x y, f (x ⊔ y) = f x ⊔ f y)

-- this looks nicer but idk if it will be easier to prove...
theorem proposition_2_19_ii' [Lattice L] [Lattice K] (f : L → K) :
  (∃ e : L ≃o K, e.toFun = f) ↔ IsLatticeIso f := by
    sorry





-- cursor agent wrote this proof (it compiles)
lemma lemma_2_22_i [PartialOrder P] (S : Set P)
  (sSupS : P) (hsSupS : IsLUB S sSupS)
  (sInfS : P) (hsInfS : IsGLB S sInfS) :
  ∀ s : S, s ≤ sSupS ∧ s ≥ sInfS := by
  intro s
  apply And.intro
  · apply hsSupS.1
    simp
  · apply hsInfS.1
    simp


-- Cursor agent with MCP and lean4-skills finished this proof
lemma lemma_2_22_ii [PartialOrder P] (S : Set P) (x : P)
  (sInfS : P) (hsInfS : IsGLB S sInfS) :
  x ≤ sInfS ↔ ∀ s : S, x ≤ s := by
  constructor
  · intro h s
    exact le_trans h (hsInfS.1 s.2)
  · intro h
    exact hsInfS.2 (by
      intro s hs
      exact h ⟨s, hs⟩)


-- written by Tally with the help of Cursor in-line suggestions
lemma lemma_2_22_iii [PartialOrder P] (S : Set P) (x : P)
  (sSupS : P) (hsSupS : IsLUB S sSupS) :
  x ≥ sSupS ↔ ∀ s : S, x ≥ s := by
  constructor
  · intro h s
    exact le_trans (hsSupS.1 s.2) h
  · intro h
    exact hsSupS.2 (by
      intro s hs
      exact h ⟨s, hs⟩)

lemma lemma_2_22_iv [PartialOrder P] (S T : Set P)
  (sSupS : P) (hsSupS : IsLUB S sSupS)
  (sInfS : P) (_hsInfS : IsGLB S sInfS)
  (sSupT : P) (_hsSupT : IsLUB T sSupT)
  (sInfT : P) (hsInfT : IsGLB T sInfT) :
  sSupS ≤ sInfT ↔ ∀ s t, s ∈ S → t ∈ T → s ≤ t := by
  constructor
  · intro h s t hs ht
    exact le_trans (hsSupS.1 hs) (le_trans h (hsInfT.1 ht))
  · intro h
    exact hsSupS.2 fun s hs => hsInfT.2 fun t ht => h s t hs ht


lemma lemma_2_22_v [PartialOrder P] (S T : Set P)
  (sSupS : P) (hsSupS : IsLUB S sSupS)
  (sInfS : P) (hsInfS : IsGLB S sInfS)
  (sSupT : P) (hsSupT : IsLUB T sSupT)
  (sInfT : P) (hsInfT : IsGLB T sInfT) :
  S ⊆ T → sSupS ≤ sSupT ∧ sInfS ≥ sInfT := by
  intro hST
  refine And.intro (IsLUB.mono hsSupS hsSupT hST) ?_
  rw [ge_iff_le]
  exact hsInfS.2 fun x hxS => hsInfT.1 (hST hxS)




/-- Lemma 2.24 (Blyth): in a lattice, every **finite nonempty** subset has a join and a meet. -/
lemma lemma_2_24 [Lattice P] (F : Set P) (hF : F.Finite) (hne : F.Nonempty) :
    (∃ sup, IsLUB F sup) ∧ (∃ inf, IsGLB F inf) := by
  classical
  have hs : hF.toFinset.Nonempty := hF.toFinset_nonempty.mpr hne
  refine And.intro ?_ ?_
  · refine ⟨hF.toFinset.sup' hs id, ?_⟩
    have h := Finset.isLUB_sup' hs
    rwa [hF.coe_toFinset] at h
  · refine ⟨hF.toFinset.inf' hs id, ?_⟩
    have h := Finset.isGLB_inf' hs
    rwa [hF.coe_toFinset] at h


/-- Same inequality as the textbook, assuming only partial orders: `p` and `q` are *some* least
upper bounds of `S` and `φ '' S`. No global `sSup` operator is needed. -/
theorem lemma_2_27_of_isLUB [PartialOrder P] [PartialOrder Q] (φ : P →o Q) (S : Set P) (p : P)
    (q : Q) (hp : IsLUB S p) (hq : IsLUB (φ '' S) q) : q ≤ φ p := by
  apply hq.2
  intro b hb
  rcases hb with ⟨a, ha, rfl⟩
  exact φ.monotone (hp.1 ha)

theorem lemma_2_27_ia [CompleteLattice P] [CompleteLattice Q] (φ : P →o Q) (S : Set P) :
    φ (sSup S) ≥ sSup (φ '' S) := by
  rw [ge_iff_le]
  exact
    lemma_2_27_of_isLUB (φ := φ) (S := S) (p := sSup S) (q := sSup (φ '' S)) (isLUB_sSup S)
      (isLUB_sSup (φ '' S))

-- TODO: check this
lemma lemma_2_30 [PartialOrder P] (hInf : ∀ S : Set P, S.Nonempty → ∃ x, IsGLB S x) :
  ∀ S : Set P, BddAbove S → ∃ x, IsLUB S x := by
    intro S hS
    have hne : (upperBounds S).Nonempty := by simpa [BddAbove, upperBounds] using hS
    obtain ⟨x, hx⟩ := hInf (upperBounds S) hne
    exact ⟨x, (isGLB_upperBounds (s := S)).1 hx⟩


theorem theorem_2_31 [PartialOrder P] :
    List.TFAE
      [Nonempty
          { cl : CompleteLattice P //
              cl.toCompleteSemilatticeSup.toPartialOrder = (inferInstance : PartialOrder P) },
        ∀ S : Set P, ∃ x, IsLUB S x,
        (∃ t : P, ∀ y, y ≤ t) ∧ ∀ S : Set P, S.Nonempty → ∃ x, IsGLB S x] := by
  tfae_have 1 → 2 := by
    rintro ⟨cl, hcl⟩
    cases hcl
    letI := cl
    intro S
    exact ⟨sSup S, isLUB_sSup S⟩
  tfae_have 2 → 3 := by sorry
  tfae_have 3 → 1 := by sorry
  tfae_finish


-- definitions of ACC and DCC
abbrev ACC (α : Type*) [LT α] : Prop := WellFoundedGT α
abbrev DCC (α : Type*) [LT α] : Prop := WellFoundedLT α

lemma lemma_2_39 [PartialOrder P] :
  ACC P ↔ ∀ A : Set P, A.Nonempty → ∃ a ∈ A, IsMax a := by
    sorry


-- TODO: check this
theorem theorem_2_40 [PartialOrder P] :
  (∀ s : Set P, IsChain (· ≤ ·) s → s.Finite) ↔ ACC P ∧ DCC P := by
    sorry


theorem theore_2_41_i [Lattice P] :
  ACC P → ∀ A : Set P, Nonempty A → ∃ (F : Finset A), Max F = Max A := by
  sorry
