import Mathlib.Order.Basic
import Mathlib.Order.Ideal
import Mathlib.Order.Lattice
import Mathlib.Order.Notation
import Mathlib.Order.SetNotation
import Mathlib.Order.CompleteLattice.Basic
import Mathlib.Order.CompleteLattice.Defs
import Mathlib.Order.Hom.CompleteLattice
import Mathlib.Order.WellFounded
import Mathlib.Order.UpperLower.Basic
import Mathlib.Order.UpperLower.CompleteLattice
import Mathlib.Tactic.TFAE
import Mathlib.Order.Preorder.Chain
import Mathlib.Order.Sublattice
import Mathlib.Data.Finset.Lattice.Fold
import Mathlib.Data.Set.Finite.Basic

variable {α β L K P Q : Type*}


-- manually completed by Tally and Alex
lemma lemma_2_8 [Lattice L] (a b : L) : List.TFAE [a ≤ b, a ⊔ b = b, a ⊓ b = a] := by
  tfae_have 1 → 2 := by
    intro h
    rw [sup_eq_right]
    exact h
  tfae_have 2 → 3 := by
    intro h
    have h' : a ⊓ (a ⊔ b) = a ⊓ b :=
      congrArg (fun x => a ⊓ x) h
    rw [inf_sup_self] at h'
    exact h'.symm
  tfae_have 3 → 1 := by
    intro h
    rw [← inf_eq_left]
    exact h
  tfae_finish


-- TODO: This proof/proof statement is not correct. It fails for general lattices
--       because it uses the fact that the lattice is totally ordered.
/-- For a **totally ordered** domain `L`, order-preserving maps preserve binary `⊓` and `⊔`.
This fails for general lattices; see e.g. Blyth, *Lattices and ordered algebraic structures* -/
theorem proposition_2_19_i [LinearOrder L] [Lattice K] (f : L → K) :
  List.TFAE [Monotone f, (∀ a b, f (a ⊓ b) = f a ⊓ f b), (∀ a b, f (a ⊔ b) = f a ⊔ f b)] := by
  tfae_have 1 → 2 := by
    intro hf a b
    rcases le_total a b with hab | hba
    · rw [inf_eq_left.2 hab]
      exact (inf_eq_left.2 (hf hab)).symm
    · rw [inf_eq_right.2 hba]
      exact (inf_eq_right.2 (hf hba)).symm
  tfae_have 2 → 3 := by
    intro h
    have hf : Monotone f := fun {x y} hxy => by
      calc
        f x = f (x ⊓ y) := by rw [inf_eq_left.2 hxy]
        _ = f x ⊓ f y := h x y
        _ ≤ f y := inf_le_right
    intro a b
    rcases le_total a b with hab | hba
    · rw [sup_eq_right.2 hab]
      exact (sup_eq_right.2 (hf hab)).symm
    · rw [sup_eq_left.2 hba]
      exact (sup_eq_left.2 (hf hba)).symm
  tfae_have 3 → 1 := by
    intro h a b hab
    rw [← sup_eq_right.2 hab, h a b]
    exact le_sup_left
  tfae_finish

-- completed by cursor agent with MCP and lean4-skills
-- ∃ e : α ≃o β, e.toFun = f means that there exists an order isomorphism between α and β
-- such that the function f is the underlying function of the order isomorphism
theorem proposition_2_19_ii [Lattice α] [Lattice β] (f : α → β) :
  (∃ e : α ≃o β, e.toFun = f) ↔
  ((Function.Bijective f) ∧
    (∀ x y, f (x ⊓ y) = f x ⊓ f y) ∧
    (∀ x y, f (x ⊔ y) = f x ⊔ f y)) := by
  constructor
  · rintro ⟨e, rfl⟩
    exact ⟨Equiv.bijective (e : α ≃ β), e.map_inf, e.map_sup⟩
  · rintro ⟨hf, _hinf, hsup⟩
    have hreflect : ∀ {a b : α}, f a ≤ f b → a ≤ b := by
      intro a b hab
      have hfb : f (a ⊔ b) = f b := by rw [hsup, sup_eq_right.2 hab]
      have hab' : a ⊔ b = b := hf.injective hfb
      rw [← hab']
      exact le_sup_left
    let e : α ≃ β := Equiv.ofBijective f hf
    refine ⟨e.toOrderIso ?_ ?_, rfl⟩
    · intro a b hab
      dsimp [e]
      rw [← sup_eq_right.2 hab, hsup]
      exact le_sup_left
    · intro a b hab
      apply hreflect
      calc
        f (e.symm a) = a := Equiv.apply_symm_apply e a
        _ ≤ b := hab
        _ = f (e.symm b) := (Equiv.apply_symm_apply e b).symm



-- definition of a lattice isomorphism generated by Cursor agent with mcp and lean4-skills
/-- `f` is a lattice isomorphism: bijective and preserves binary meet and join -/
def IsLatticeIso [Lattice α] [Lattice β] (f : α → β) : Prop :=
  Function.Bijective f ∧ (∀ x y, f (x ⊓ y) = f x ⊓ f y) ∧ (∀ x y, f (x ⊔ y) = f x ⊔ f y)



-- cursor agent wrote this proof (it compiles)
lemma lemma_2_22_i [PartialOrder P] (S : Set P)
  (sSupS : P) (hsSupS : IsLUB S sSupS)
  (sInfS : P) (hsInfS : IsGLB S sInfS) :
  ∀ s : S, s ≤ sSupS ∧ s ≥ sInfS := by
  intro s
  apply And.intro
  · apply hsSupS.1
    simp
  · apply hsInfS.1
    simp


-- Cursor agent with MCP and lean4-skills finished this proof
lemma lemma_2_22_ii [PartialOrder P] (S : Set P) (x : P)
  (sInfS : P) (hsInfS : IsGLB S sInfS) :
  x ≤ sInfS ↔ ∀ s : S, x ≤ s := by
  constructor
  · intro h s
    exact le_trans h (hsInfS.1 s.2)
  · intro h
    exact hsInfS.2 (by
      intro s hs
      exact h ⟨s, hs⟩)


-- written by Tally with the help of Cursor in-line suggestions
lemma lemma_2_22_iii [PartialOrder P] (S : Set P) (x : P)
  (sSupS : P) (hsSupS : IsLUB S sSupS) :
  x ≥ sSupS ↔ ∀ s : S, x ≥ s := by
  constructor
  · intro h s
    exact le_trans (hsSupS.1 s.2) h
  · intro h
    exact hsSupS.2 (by
      intro s hs
      exact h ⟨s, hs⟩)

lemma lemma_2_22_iv [PartialOrder P] (S T : Set P)
  (sSupS : P) (hsSupS : IsLUB S sSupS)
  (sInfS : P) (_hsInfS : IsGLB S sInfS)
  (sSupT : P) (_hsSupT : IsLUB T sSupT)
  (sInfT : P) (hsInfT : IsGLB T sInfT) :
  sSupS ≤ sInfT ↔ ∀ s t, s ∈ S → t ∈ T → s ≤ t := by
  constructor
  · intro h s t hs ht
    exact le_trans (hsSupS.1 hs) (le_trans h (hsInfT.1 ht))
  · intro h
    exact hsSupS.2 fun s hs => hsInfT.2 fun t ht => h s t hs ht


lemma lemma_2_22_v [PartialOrder P] (S T : Set P)
  (sSupS : P) (hsSupS : IsLUB S sSupS)
  (sInfS : P) (hsInfS : IsGLB S sInfS)
  (sSupT : P) (hsSupT : IsLUB T sSupT)
  (sInfT : P) (hsInfT : IsGLB T sInfT) :
  S ⊆ T → sSupS ≤ sSupT ∧ sInfS ≥ sInfT := by
  intro hST
  refine And.intro (IsLUB.mono hsSupS hsSupT hST) ?_
  rw [ge_iff_le]
  exact hsInfS.2 fun x hxS => hsInfT.1 (hST hxS)




/-- Lemma 2.24 (Blyth): in a lattice, every **finite nonempty** subset has a join and a meet. -/
lemma lemma_2_24 [Lattice P] (F : Set P) (hF : F.Finite) (hne : F.Nonempty) :
    (∃ sup, IsLUB F sup) ∧ (∃ inf, IsGLB F inf) := by
  classical
  have hs : hF.toFinset.Nonempty := hF.toFinset_nonempty.mpr hne
  refine And.intro ?_ ?_
  · refine ⟨hF.toFinset.sup' hs id, ?_⟩
    have h := Finset.isLUB_sup' hs
    rwa [hF.coe_toFinset] at h
  · refine ⟨hF.toFinset.inf' hs id, ?_⟩
    have h := Finset.isGLB_inf' hs
    rwa [hF.coe_toFinset] at h


/-- Same inequality as the textbook, assuming only partial orders: `p` and `q` are *some* least
upper bounds of `S` and `φ '' S`. No global `sSup` operator is needed. -/
theorem lemma_2_27_of_isLUB [PartialOrder P] [PartialOrder Q] (φ : P →o Q) (S : Set P) (p : P)
    (q : Q) (hp : IsLUB S p) (hq : IsLUB (φ '' S) q) : q ≤ φ p := by
  apply hq.2
  intro b hb
  rcases hb with ⟨a, ha, rfl⟩
  exact φ.monotone (hp.1 ha)

theorem lemma_2_27_ia [CompleteLattice P] [CompleteLattice Q] (φ : P →o Q) (S : Set P) :
    φ (sSup S) ≥ sSup (φ '' S) := by
  rw [ge_iff_le]
  exact
    lemma_2_27_of_isLUB (φ := φ) (S := S) (p := sSup S) (q := sSup (φ '' S)) (isLUB_sSup S)
      (isLUB_sSup (φ '' S))



-- page 47
lemma lemma_2_30 [PartialOrder P] (_S : Set P) (hInf : ∀ S : Set P, S.Nonempty →
  ∃ x, IsGLB S x) : ∀ S : Set P, BddAbove S → ∃ x, IsLUB S x := by
  intro S hS
  have hne : (upperBounds S).Nonempty := by simpa [BddAbove, upperBounds] using hS
  obtain ⟨x, hx⟩ := hInf (upperBounds S) hne
  exact ⟨x, (isGLB_upperBounds (s := S)).1 hx⟩


theorem theorem_2_31 [PartialOrder P] :
    List.TFAE
      [Nonempty
          { cl : CompleteLattice P //
              cl.toCompleteSemilatticeSup.toPartialOrder = (inferInstance : PartialOrder P) },
        ∀ S : Set P, ∃ x, IsLUB S x,
        (∃ t : P, ∀ y, y ≤ t) ∧ ∀ S : Set P, S.Nonempty → ∃ x, IsGLB S x] := by
  tfae_have 1 → 2 := by
    rintro ⟨cl, hcl⟩
    cases hcl
    letI := cl
    intro S
    exact ⟨sSup S, isLUB_sSup S⟩
  tfae_have 2 → 3 := by sorry
  tfae_have 3 → 1 := by sorry
  tfae_finish

-- should this be a lemma?
-- page 52
theorem lemma_2_39 [PartialOrder P] :
  WellFoundedGT P ↔ ∀ A : Set P, A.Nonempty → ∃ a ∈ A, IsMax a := by
  constructor
  -- the first intro was written by Cursor agent and compiles without error
  · intro h A nonempty_A
    obtain ⟨a₁, ha₁, hmin⟩ := h.wf.has_min A nonempty_A
    exact ⟨a₁, ha₁, sorry⟩
  · intro h
    sorry



-- this does not feel correct. It could definitely be improved/simplified
theorem exercise_2_6_i [PartialOrder P] [InfSet P] (A : Set P) (hInf : ∃ x, IsGLB A x) :
  Set.sInter ((fun a : P => (Order.Ideal.principal a : Set P)) '' A) =
    (Order.Ideal.principal (sInf A) : Set P) := by
  sorry


theorem exercise_2_11 [Lattice L] :
    List.TFAE
      [IsChain (· ≤ ·) (Set.univ : Set L), -- Cursor wrote this line
        ∀ S : Set L, S.Nonempty → IsSublattice S,
        ∀ a b : Set L, IsSublattice (a ∪ b)] := by
  sorry


-- Cursor fixed the proof statement and proved it
theorem exercise_2_19_i [Lattice L] [Lattice K] (S : Sublattice L) (M : L) (f : LatticeHom L K)
    (hM : M ∈ S) : f M ∈ S.map f :=
  S.mem_map_of_mem f hM


-- theorem exercise_2_19_ii [Lattice L] [Lattice K] (S : Sublattice K) (N : K) (f : LatticeHom L K)
--     (hN : N ∈ S) : N ∈ S.comap f :=
--   S.mem_comap.mpr hN
